global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'python-web-app'
    static_configs:
      - targets: ['python-web-2:80']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongo-exporter:9216']
    scrape_interval: 10s
    metrics_path: /metrics
  
alerting:
  alertmanagers:
    - static_configs:
      - targets: